/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Blueprint: The Journey',
      collapsed: false, // Taake ye humesha khula nazar aaye
      link: {
        type: 'generated-index',
        title: 'Project Blueprint',
        description: 'The complete step-by-step guide to our AI-Native application.',
        slug: 'blueprint-journey', // URL ab /docs/category/blueprint-journey banega
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.', // Yeh jadoo hai ✨: docs folder ke saare sub-folders automatic categories ban jayenge
        },
      ],
    },
  ],
};

export default sidebars;