openapi: 3.1.0
info:
  title: AI-Native Book Generator API
  version: 1.0.0
  description: API contract for generating and deploying Docusaurus books from raw content.
paths:
  /generate-book:
    post:
      summary: Generate Docusaurus Project
      operationId: generateBook
      tags:
        - Book Creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - source_content_paths
                - output_directory
              properties:
                source_content_paths:
                  type: array
                  items:
                    type: string
                  description: List of absolute paths to source markdown/pdf files.
                output_directory:
                  type: string
                  description: Target directory for the Docusaurus project.
      responses:
        "200":
          description: Project successfully generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocusaurusProject"
        "422":
          description: Validation Error
        "500":
          description: Server Error during generation

  /deploy-book:
    post:
      summary: Deploy Book to GitHub Pages
      operationId: deployBook
      tags:
        - Deployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - project_id
              properties:
                project_id:
                  type: string
                  description: ID of the generated project to deploy.
      responses:
        "200":
          description: Deployment successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneratedBook"

components:
  schemas:
    DocusaurusProject:
      type: object
      properties:
        id:
          type: string
        project_path:
          type: string
        config_files:
          type: array
          items:
            type: string
        content_files:
          type: array
          items:
            type: string
        creation_timestamp:
          type: string
          format: date-time

    GeneratedBook:
      type: object
      properties:
        id:
          type: string
        output_path:
          type: string
        deployment_url:
          type: string
          format: uri
        build_timestamp:
          type: string
          format: date-time
